# Generic exceptions
def validation_error(ValueError):
    pass
